name: "Snyk Scan"

on:
  push:
    branches:
      - 'demo*'  # Include any branch starting with demo

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Scan'
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v1

      # Install and Authenticate to Snyk
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          sudo npm install -g snyk-delta
          snyk auth ${SNYK_TOKEN}

      # Run Snyk OS
      - name: Run Snyk OS
        run: |
          snyk test --json --print-deps | snyk-delta ---baselineOrg de3458ab-2cde-4291-b24a-4ae706939a85 --baselineProject 7537823e-2573-4c86-8b64-2f73bc81148b --setPassIfNoBaseline true
        continue-on-error: true
